apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-example-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-example-app
  template:
    metadata:
      labels:
        app: argocd-example-app
    spec:
      containers:
      - name: argocd-example-app
        image: public.ecr.aws/g7p6k1i5/buoysoftware/example-app:latest
        ports:
        - containerPort: 3000
      tolerations:
      - key: "node_type"
        effect: "NoExecute"
        value: "worker"
      - key: "provisioner"
        value: "buoy-pltf-use1-provisioner"
        effect: "NoExecute"
